# Site
title: 'The Cybersecurity Librarian'
description: 'Cataloguing Threats, Classifying Risks, and Building Security Literacy'
email: 'michael@cyberlibrarian.ca'
github_username: 'cyberlibrarian'
baseurl: ''
url: 'https://cyberlibrarian.ca'
show_excerpts: true
logo: 'assets/images/logo.png'
  
# custom Variables for my site
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
lang: en-us

author:
    name: "Michael McDonnell"
    email: "michael@cyberlibrarian.ca"

# minima
minima:
    date_format: "%Y-%m-%d"
    social_links:
      - { platform: github, user_url: "https://github.com/cyberlibrarian" }
      - { platform: mastodon, user_url: "https://infosec.exchange/@cyberlibrarian" }
      - { platform: linkedin, user_url: "https://linkedin.com/in/itpromichael" }
      - { platform: youtube, user_url: "https://www.youtube.com/c/cyberlibrarian" }

header_pages:
    - _pages/learning.md
    - _pages/moro-and-mike.md

include:
  - _pages

defaults:
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
theme: 'minima'
#remote_theme: pages-themes/minimal
#highlighter: rouge

# Plugins
plugins: 
  - jekyll-feed
#  - jekyll-sitemap
#  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

